### ISSUE TITLE
Deprecation in favor of tempfile

### ISSUE THREAD

**Issue by Nukesor** [la10736/temp_testdir#4]
Hi @la10736 

I've noticed that this library hasn't received any updates since over two years.

In order to keep the Rust ecosystem clean, would you mind setting this crate on `deprecated`, adding a deprecation notice and redirecting to the [tempfile](https://github.com/Stebalien/tempfile) project in your README?

**Comment by la10736** [comment]
You are right but this crate don't have the same target of `tempfile` crate. This crate is _designed_ with tests in mind: you can chose temp root dir and you can chose to not delete these file at the end (to analyze the content after tests).

I wrote it for use it in `rstest`'s tests.

**Comment by Nukesor** [comment]
These are fair points.

I guess it would make sense to patch `tempfile` with that functionality. I'll check whether they're interested in such behavior and I might create a PR that adds this functionality to `tempfile`.

**Comment by Nukesor** [comment]
There are now PRs for both requested features in the `tempfile` project.

https://github.com/Stebalien/tempfile/pull/170
https://github.com/Stebalien/tempfile/issues/169

**Comment by la10736** [comment]
WOW, thanks very much. I'll switch to `tempfile` and deprecate `temp_testdir` when your PR will merge and the new version land.

**Comment by la10736** [comment]
Ok, thanks for your effort to try to keep things cleaner. Unfortunately I've designed this crate with just tests in mind and and not a general purpose use. I understand that tempfile cannot add these features.
